Added code to tune SVC
UBC-MDS/wine_quality_predictor_group1 pull request #5
Opened 2024-11-22 21:54 UTC by wzhu8410

Hi team, I added code to tune for parameters of SVC, which I think is the best performing model from the results by Timothy. iteration=100 takes too long and I have reduced it to 50, but we can add back later. Also do we need to set random state, to make it more realistic? Let me know if there's any other feed back or questions. Thanks!

2024-11-22 22:06 UTC, yixuangaoclara commented
Hi, it looks good. We can keep iteration=50 for now, and I think we can set the random state = 123.

2024-11-22 23:09 UTC, SimplyTim commented on notebooks/wine_predictor_analysis_report.ipynb
> +    "                                   n_iter=50, cv=5, n_jobs=-1, random_state=123) #Do we want random_state?\n",
As per group discussion, I don't think we are going forward with the random_state.
```suggestion
    "                                   n_iter=50, cv=5, n_jobs=-1) #Do we want random_state?\n",
```

2024-11-22 23:13 UTC, SimplyTim commented on notebooks/wine_predictor_analysis_report.ipynb
> +    "    'svc__kernel': ['linear', 'rbf', 'poly'],\n",
Since we mentioned specifically SVM RBF in analysis, maybe we should not include this hyperparameter?

2024-11-22 23:13 UTC, SimplyTim reviewed
I made a few comments on the hyperparameter tuning. Let me know what you think.

2024-11-23 00:01 UTC, BryanLee06 approved these changes
Looks good to me!

2024-11-23 00:06 UTC, SimplyTim commented on notebooks/wine_predictor_analysis_report.ipynb
> +    "    'svc__kernel': ['linear', 'rbf', 'poly'],\n",
```suggestion

```

2024-11-23 00:07 UTC, SimplyTim commented on notebooks/wine_predictor_analysis_report.ipynb
> +    "    'svc__kernel': ['linear', 'rbf', 'poly'],\n",
If we are specifically dealing with RBF kernel, we shouldn't vary the kernel.

2024-11-23 00:08 UTC, SimplyTim requested changes
Changes to hyperparameter tuning.

2024-11-23 00:10 UTC, merged